#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 44f7d293-304e-41bd-a739-559973f2d662
# Source File: ..\PSFixXML.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
7gEAAB+LCAAAAAAABACNkV1LwzAUhu8H+w8l9zX92kohzYWbFcHp2IZ4J1l7KpE0KUkr2783tZl0
COJdnuTN85ITsoNSfYI+r1nH6HzmeWSr1QeU3TdYfAFtuJI0JPiydCcFF/CwpklSp1WUxX4cJOAn
4bHyWRpn/mKRZWlcR9VyGRHswu6q6zicW6ABwVOcyI0Dh94OatAgS3hiDeQIebc9F1WOAkT3HdNd
3960xoxdf19dMSH8DeOyULp5a009dV32raz+t+xeqCMTVhVOVN5KNQ2T1d2pAzmMLkcH3QOiY9rY
hvCqYYTx3T9jGelZ83cumRgCQy/d7gt+et08WklrgwT/SsxnBF/97xeM/F/v7gEAAA==#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2014 v4.1.58
     Generated on:       19.09.2019 18:08
     Generated by:       Pashkov-KM
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2014
#>


#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
xQQAAB+LCAAAAAAABAC9lMlqwzAQQO+F/oPJ2Xip4jgBxxBSciltQ13aXsf22IhqCSM5wX9fZyEJ
LXQJ1Ogyo5Hm8ZCY5AkLvUZqb8GC0wWGazUd3AzS6yvHSR6J11yBWHCBDyAxzSyQbVbeypjE/1Ld
3ZkZgzIXHM0uP+20adYai9K7BwU1SlTWmzVWS7Ad1HVeDnTmBdvlOvNG2IZwqrCxBMJ1lk3Xt7jD
9lm/Y3cwzCs2jkZQstEQWZT4R9JnsjSFJsHzE2X4W0oexxAV0SicsCEG48k3lL1fHwzvlatSb4y3
0CRNL8TtD+kHRLDhqr6EFbAqquIqDMsoAAY/s96k6MeJExZWU5shrXmBFz3Zn+3mmrAXvYPVknSn
9g9ux3Q/VRL/fGylH3nEhp/FBAAA#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
	Param ([String]$Commandline)
	#Note: This function starts the application
	#Note: $Commandline contains the complete argument string passed to the packager 
	#Note: To get the script directory in the Packager use: Split-Path $hostinvocation.MyCommand.path
	#Note: To get the console output in the Packager (Forms Mode) use: $ConsoleOutput (Type: System.Collections.ArrayList)
	#TODO: Initialize and add Function calls to forms
	
	if((Call-MainForm_psf) -eq "OK")
	{
		
	}
	
	$global:ExitCode = 0 #Set the exit code for the Packager
}






#endregion Source: Startup.pss

#region Source: MainForm.psf
function Call-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
vjEAAB+LCAAAAAAABADdW11z2jgUfd+Z/Q8ePzN8GUiYIcwkpOl2NrSZQLN96wgjQBsjeWQ5hP31
e2WbYLBsyy64aScdUhsd36t7j46kK2fwiG32gvn2FglkwH88wuiV2TaHf/5hGIMvnCwJRc4dcfBn
tMbDMSL0jvF13fUWg0bi6xA0+xfbwhBbF1+Zk60n8Lr+D6FztvHqEht+1gzVVzXjKfKhU2/Kn5ox
8h3hc3xFsS84cmrGgz9ziP033k7ZM6ZXs4sL1LW7vVbf6uDmZd80KLhyZe5cNQ17RZw5h6bmiFHB
meOF3QNfHzhzMRfbCDNyCKZiQv7D5rDfa9WM7qU1aOwapYDGhJK1vw5RvSa4DB+5KBkv8y2euc0n
K7b5ZDNqDu+Q4+H89gJx8cA8IogEjaBbmE9sjjHNxU7xqzCH38b3xiPaGE8EbzBPgj68wDMjxD1D
c3P4hcrfsjvBd4NG8GvXPp8WUzSLEnR2cgg0s0NTrSx+JGNz7boYcURtSN6dg8SNLwSjXiI8SeQt
s58BQxxHo/EdOALsIDZnHlsIY4KoZ0wwJ4ua0WrW211XaDzlntkozD+EKknJNFLGgqOBmWAH8orn
n+gcv4IlHUhsgFl9DQAwI3p8R9Vai1oPaImr4JULdnJIlZWpTs1oq0KSkazAohbkAc3nhC7NoVUz
on9auChhXQB0mz0tyD5lKkakiY78DBRHC/PVw0/E85EzEVsH3yD7ecQcxuEx3E9KpCZVPnLmuzfs
9excWUpDM/aaSxaFCvmCyZyM2RzyAh5vrul8suKEPiu7XVCNshkKJGi12pqwkKRvXdVERXzrXABB
+7qgbJFIQUwEc9PmVG3KPBJ7JZlbBWs42BJgS484iiUOtAP4GFN/Ijhxj9sD4hEvMDzTxhHEDiFr
gHgSAnYbx1bUsVPwDgsI5lcuHc2KegnG5nFWrarppI1HWhu6Yy5MbVZP3+Keu2kDK00xtfIAS/WA
xHElVNx6h+LYLi6OIVGmzC2jbOr5ME/XdNUwpmutZho70rmhnnnL6pqSTjC+YKNgCLQsL4cjtp6x
KkhiS0MQfrlaDpYAZQTxFi5v2YaGDxjuLu+Jp1piq58hO4aEgKXVB4pmDp5nLEFyKNgE5Wh3C0pV
IhAF9arVaxayuqfkZTomvkE82CSMVoguZYwSbn9XtTvcR0YPT6rX+6XmHVoTZ/vrc7MHHNGfnpLM
DONQkJrtC6skNS9ORc3Q77NzMywlnJ2Zs8BM2JkynDzSql5RrYrbLyVTaVN0mZkzbRos6F7xjWiC
hiPI3fNhdL4H905JsSkH124QP38dRBqaIV5qi3JN7VUQPObWjHu8EDXjkSxX+unYU7QbTKf6ojVG
r7KWK4H6mLD+C/TUx0S1m12UCo6DjtxedArsFN7GQYGxA9SLph3Ig8yCNvQJOT7ODseBANtACicW
je/hHRXxj6Bj5nv4L3mAEYfv75507FS0wY+2nOFCfIqWP6bRvRIKfexBqRm7jEqnOaqzfU3eeHdV
YavyqrBedfenVIXV6pVSFeYY/+SqsHRBelDBzInxCxgqURX+sZpuscrHm5vFKx9dxeloHltSjjdy
ROD4Mj/NE4GE71WxQvICS/lLpMwzPb3TszBje4PFTug6yiO3ZHtQkI9BPTmt6FQkuweZO7zQ2eQf
lrgr2OwnCuT67xx8As/i+ZbXmUrEmBN0S/ZPNj5f9+JD7fhQwAu2KNeOk/AnfjowaMg7v1znbOZu
f8d+uQhs/o4dsx2MuH7HNN/OSYzrXNwjBkXj4bFsGAe9N3vWsFgbI74k+i/4hBWRVr9m9I/XUkUF
s8IkZg6wnGQoINphulSWAdTLzRFYMnbVvuwXn6KqjdK3ZPnm/eclRSAyE6PGnCUzD9KUVkbUTv2K
KcmYaDPTko47S2rC8WJcKzYfqvyke3eaHE0rWPYJsCNir0O8S/qkzIzZUqvEnEdrpSk9jVU6lceW
a8/DawgU9naPju5so/m5PkYUJl+Y40Vdvla1DnZX+wRYugmwWrOFddntobnV62CrO2i8WTq2vPZs
xh0yO0GaM6yE/avCxsnJm29Rvq9ejSGONrC1LWOraS26i4tFqzXvNpGF8m19WzvV9IlwGCCMbyeY
vxAbl0pZ4d6NGMeVdC/qFWgKdK2avt1ijyzp6U29XYYCNmjE/15j+D+oEMuXvjEAAA==#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$MainForm = New-Object 'System.Windows.Forms.Form'
	$tabcontrol1 = New-Object 'System.Windows.Forms.TabControl'
	$tabpage1 = New-Object 'System.Windows.Forms.TabPage'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$richtextbox1 = New-Object 'System.Windows.Forms.RichTextBox'
	$groupbox2 = New-Object 'System.Windows.Forms.GroupBox'
	$comboboxFontStyle = New-Object 'System.Windows.Forms.ComboBox'
	$comboboxFontFamily = New-Object 'System.Windows.Forms.ComboBox'
	$buttonSelect = New-Object 'System.Windows.Forms.Button'
	$trackbar1 = New-Object 'System.Windows.Forms.TrackBar'
	$textboxFilterTag = New-Object 'System.Windows.Forms.TextBox'
	$tabpage3 = New-Object 'System.Windows.Forms.TabPage'
	$treeview1 = New-Object 'System.Windows.Forms.TreeView'
	$statusbar1 = New-Object 'System.Windows.Forms.StatusBar'
	$contextmenustrip1 = New-Object 'System.Windows.Forms.ContextMenuStrip'
	$copyToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$pasteToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$selectAllToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$tooltip1 = New-Object 'System.Windows.Forms.ToolTip'
	$clearToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$OnLoadFormEvent = {
		$richtextbox1.RightMargin = [System.Windows.Forms.Screen]::PrimaryScreen.WorkingArea.Width * 1000
		$richtextbox1.Select()
		$comboboxFontFamily.Items.AddRange(@([System.Drawing.FontFamily]::Families.Name))
		$comboboxFontFamily.SelectedIndex = 0
	}
	
	$richtextbox1_TextChanged={
		& $trackbar1_Scroll
	}
	$trackbar1_Scroll={
		$richtextbox1.Font = New-Object -TypeName System.Drawing.Font([System.Drawing.FontFamily]$($comboboxFontFamily.SelectedItem), [float]$($trackbar1.Value), [System.Drawing.FontStyle]$($comboboxFontStyle.SelectedItem))
		$richtextbox1.Select()
	}
	
	$trackbar1_MouseHover={
		$tooltip1.Show($richtextbox1.Font,$trackbar1)
	}
	
	$buttonSelect_Click = {
		try
		{
			$statusbar1.Text = [System.String]::Empty
			$OriginalText = $richtextbox1.Text.ToString()
			
			$FilteredText = Get-XMLData -Text $richtextbox1.Text.ToString().Trim() -FilterTag $textboxFilterTag.Text.ToString().Trim()
			$FixedXML = Fix-XML -Text $FilteredText
			$FormatText = Format-XML -XML $FixedXML
			$richtextbox1.Text = $FormatText
			
			[xml]$xml = $FixedXML
			
			$treeview1.Nodes.Clear();
			ConvertXmlNodeTo-TreeNode $xml -TreeNode $treeview1.Nodes
			$treeview1.Nodes[0].ExpandAll()
		}
		catch
		{
			$richtextbox1.Text = $OriginalText
			$statusbar1.Text = $Error[0].Exception.Message
		}
	}
	
	$selectAllToolStripMenuItem_Click={
		$richtextbox1.SelectAll()
	}
	
	$copyToolStripMenuItem_Click = {
		$richtextbox1.Copy()
	}
	
	$pasteToolStripMenuItem_Click = {
		[System.Windows.Forms.IDataObject]$idata = [System.Windows.Forms.Clipboard]::GetDataObject()
		$richtextbox1.SelectedText = $idata.GetData([System.Windows.Forms.DataFormats]::Text)
	}
	
	$clearToolStripMenuItem_Click={
		$richtextbox1.Clear()
	}
	$comboboxFontFamily_SelectedIndexChanged = {
		$comboboxFontStyle.Items.Clear()
		
		$i = 0
		do
		{
			$font = [System.Drawing.FontFamily]::Families.Get($i)
			$i++
		}
		while ($comboboxFontFamily.SelectedItem -ne $font.Name)
		
		foreach ($style in @([System.Drawing.FontStyle]::GetNames([System.Drawing.FontStyle])))
		{
			if ($font.IsStyleAvailable($style))
			{
				$comboboxFontStyle.Items.Add($style)
			}
		}
		
		$comboboxFontStyle.SelectedIndex = 0
	}
	
	$comboboxFontStyle_SelectedIndexChanged={
		& $trackbar1_Scroll
	}
		# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$MainForm.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_richtextbox1 = $richtextbox1.Text
		$script:MainForm_comboboxFontStyle_SelectedItem = $comboboxFontStyle.SelectedItems
		$script:MainForm_comboboxFontFamily_SelectedItem = $comboboxFontFamily.SelectedItems
		$script:MainForm_trackbar1 = $trackbar1.Value
		$script:MainForm_textboxFilterTag = $textboxFilterTag.Text
		if($treeview1.SelectedNode -ne $null)
		{
			$script:MainForm_treeview1 = $treeview1.SelectedNode.Text
		}
		else
		{
			$script:MainForm_treeview1 = $null
		}
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$comboboxFontStyle.remove_SelectedIndexChanged($comboboxFontStyle_SelectedIndexChanged)
			$comboboxFontFamily.remove_SelectedIndexChanged($comboboxFontFamily_SelectedIndexChanged)
			$buttonSelect.remove_Click($buttonSelect_Click)
			$trackbar1.remove_Scroll($trackbar1_Scroll)
			$trackbar1.remove_MouseHover($trackbar1_MouseHover)
			$MainForm.remove_Load($OnLoadFormEvent)
			$copyToolStripMenuItem.remove_Click($copyToolStripMenuItem_Click)
			$pasteToolStripMenuItem.remove_Click($pasteToolStripMenuItem_Click)
			$selectAllToolStripMenuItem.remove_Click($selectAllToolStripMenuItem_Click)
			$clearToolStripMenuItem.remove_Click($clearToolStripMenuItem_Click)
			$MainForm.remove_Load($Form_StateCorrection_Load)
			$MainForm.remove_Closing($Form_StoreValues_Closing)
			$MainForm.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$MainForm.SuspendLayout()
	$tabcontrol1.SuspendLayout()
	$tabpage1.SuspendLayout()
	$groupbox1.SuspendLayout()
	$groupbox2.SuspendLayout()
	$trackbar1.BeginInit()
	$tabpage3.SuspendLayout()
	#
	# MainForm
	#
	$MainForm.Controls.Add($tabcontrol1)
	$MainForm.Controls.Add($statusbar1)
	$MainForm.ClientSize = '961, 583'
	$MainForm.MinimumSize = '600, 600'
	$MainForm.Name = "MainForm"
	$MainForm.ShowIcon = $False
	$MainForm.StartPosition = 'CenterScreen'
	$MainForm.Text = "XML Raw Viewer"
	$MainForm.add_Load($OnLoadFormEvent)
	#
	# tabcontrol1
	#
	$tabcontrol1.Controls.Add($tabpage1)
	$tabcontrol1.Controls.Add($tabpage3)
	$tabcontrol1.Appearance = 'FlatButtons'
	$tabcontrol1.Dock = 'Fill'
	$tabcontrol1.Font = "Microsoft Sans Serif, 10.25pt"
	$tabcontrol1.Location = '0, 0'
	$tabcontrol1.Name = "tabcontrol1"
	$tabcontrol1.SelectedIndex = 0
	$tabcontrol1.Size = '961, 539'
	$tabcontrol1.TabIndex = 4
	#
	# tabpage1
	#
	$tabpage1.Controls.Add($groupbox1)
	$tabpage1.Controls.Add($groupbox2)
	$tabpage1.Location = '4, 29'
	$tabpage1.Name = "tabpage1"
	$tabpage1.Padding = '3, 3, 3, 3'
	$tabpage1.Size = '953, 506'
	$tabpage1.TabIndex = 0
	$tabpage1.Text = "Text View"
	$tabpage1.UseVisualStyleBackColor = $True
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($richtextbox1)
	$groupbox1.AutoSizeMode = 'GrowAndShrink'
	$groupbox1.Dock = 'Fill'
	$groupbox1.Location = '3, 112'
	$groupbox1.Name = "groupbox1"
	$groupbox1.Size = '947, 391'
	$groupbox1.TabIndex = 4
	$groupbox1.TabStop = $False
	#
	# richtextbox1
	#
	$richtextbox1.ContextMenuStrip = $contextmenustrip1
	$richtextbox1.DetectUrls = $False
	$richtextbox1.Dock = 'Fill'
	$richtextbox1.Location = '3, 19'
	$richtextbox1.Name = "richtextbox1"
	$richtextbox1.Size = '941, 369'
	$richtextbox1.TabIndex = 2
	$richtextbox1.Text = ""
	#
	# groupbox2
	#
	$groupbox2.Controls.Add($comboboxFontStyle)
	$groupbox2.Controls.Add($comboboxFontFamily)
	$groupbox2.Controls.Add($buttonSelect)
	$groupbox2.Controls.Add($trackbar1)
	$groupbox2.Controls.Add($textboxFilterTag)
	$groupbox2.Dock = 'Top'
	$groupbox2.Location = '3, 3'
	$groupbox2.Name = "groupbox2"
	$groupbox2.Size = '947, 109'
	$groupbox2.TabIndex = 6
	$groupbox2.TabStop = $False
	$groupbox2.Text = "Filter tag"
	#
	# comboboxFontStyle
	#
	$comboboxFontStyle.DropDownStyle = 'DropDownList'
	$comboboxFontStyle.FormattingEnabled = $True
	$comboboxFontStyle.Location = '301, 25'
	$comboboxFontStyle.Name = "comboboxFontStyle"
	$comboboxFontStyle.Size = '160, 25'
	$comboboxFontStyle.TabIndex = 8
	$comboboxFontStyle.add_SelectedIndexChanged($comboboxFontStyle_SelectedIndexChanged)
	#
	# comboboxFontFamily
	#
	$comboboxFontFamily.DropDownStyle = 'DropDownList'
	$comboboxFontFamily.FormattingEnabled = $True
	$comboboxFontFamily.Location = '6, 22'
	$comboboxFontFamily.Name = "comboboxFontFamily"
	$comboboxFontFamily.Size = '273, 25'
	$comboboxFontFamily.TabIndex = 7
	$comboboxFontFamily.add_SelectedIndexChanged($comboboxFontFamily_SelectedIndexChanged)
	#
	# buttonSelect
	#
	$buttonSelect.Location = '301, 65'
	$buttonSelect.Name = "buttonSelect"
	$buttonSelect.Size = '160, 23'
	$buttonSelect.TabIndex = 6
	$buttonSelect.Text = "Select"
	$buttonSelect.UseVisualStyleBackColor = $True
	$buttonSelect.add_Click($buttonSelect_Click)
	#
	# trackbar1
	#
	$trackbar1.Anchor = 'Top, Left, Right'
	$trackbar1.Location = '501, 22'
	$trackbar1.Maximum = 50
	$trackbar1.Minimum = 10
	$trackbar1.Name = "trackbar1"
	$trackbar1.Size = '441, 42'
	$trackbar1.TabIndex = 3
	$trackbar1.TickStyle = 'TopLeft'
	$trackbar1.Value = 10
	$trackbar1.add_Scroll($trackbar1_Scroll)
	$trackbar1.add_MouseHover($trackbar1_MouseHover)
	#
	# textboxFilterTag
	#
	$textboxFilterTag.Location = '6, 65'
	$textboxFilterTag.Name = "textboxFilterTag"
	$textboxFilterTag.Size = '273, 23'
	$textboxFilterTag.TabIndex = 5
	#
	# tabpage3
	#
	$tabpage3.Controls.Add($treeview1)
	$tabpage3.Location = '4, 29'
	$tabpage3.Name = "tabpage3"
	$tabpage3.Padding = '3, 3, 3, 3'
	$tabpage3.Size = '953, 506'
	$tabpage3.TabIndex = 2
	$tabpage3.Text = "Tree View"
	$tabpage3.UseVisualStyleBackColor = $True
	#
	# treeview1
	#
	$treeview1.Dock = 'Fill'
	$treeview1.Location = '3, 3'
	$treeview1.Name = "treeview1"
	$treeview1.Size = '947, 500'
	$treeview1.TabIndex = 1
	#
	# statusbar1
	#
	$statusbar1.Location = '0, 539'
	$statusbar1.Name = "statusbar1"
	$statusbar1.Size = '961, 44'
	$statusbar1.SizingGrip = $False
	$statusbar1.TabIndex = 1
	#
	# contextmenustrip1
	#
	[void]$contextmenustrip1.Items.Add($selectAllToolStripMenuItem)
	[void]$contextmenustrip1.Items.Add($copyToolStripMenuItem)
	[void]$contextmenustrip1.Items.Add($pasteToolStripMenuItem)
	[void]$contextmenustrip1.Items.Add($clearToolStripMenuItem)
	$contextmenustrip1.Name = "contextmenustrip1"
	$contextmenustrip1.RenderMode = 'System'
	$contextmenustrip1.ShowImageMargin = $False
	$contextmenustrip1.Size = '119, 92'
	#
	# copyToolStripMenuItem
	#
	$copyToolStripMenuItem.Name = "copyToolStripMenuItem"
	$copyToolStripMenuItem.Size = '118, 22'
	$copyToolStripMenuItem.Text = "Copy Selected"
	$copyToolStripMenuItem.add_Click($copyToolStripMenuItem_Click)
	#
	# pasteToolStripMenuItem
	#
	$pasteToolStripMenuItem.Name = "pasteToolStripMenuItem"
	$pasteToolStripMenuItem.Size = '118, 22'
	$pasteToolStripMenuItem.Text = "Paste"
	$pasteToolStripMenuItem.add_Click($pasteToolStripMenuItem_Click)
	#
	# selectAllToolStripMenuItem
	#
	$selectAllToolStripMenuItem.Name = "selectAllToolStripMenuItem"
	$selectAllToolStripMenuItem.Size = '118, 22'
	$selectAllToolStripMenuItem.Text = "Select All"
	$selectAllToolStripMenuItem.add_Click($selectAllToolStripMenuItem_Click)
	#
	# tooltip1
	#
	#
	# clearToolStripMenuItem
	#
	$clearToolStripMenuItem.Name = "clearToolStripMenuItem"
	$clearToolStripMenuItem.Size = '118, 22'
	$clearToolStripMenuItem.Text = "Clear"
	$clearToolStripMenuItem.add_Click($clearToolStripMenuItem_Click)
	$tabpage3.ResumeLayout($false)
	$trackbar1.EndInit()
	$groupbox2.ResumeLayout($false)
	$groupbox1.ResumeLayout($false)
	$tabpage1.ResumeLayout($false)
	$tabcontrol1.ResumeLayout($false)
	$MainForm.ResumeLayout($false)
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $MainForm.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$MainForm.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$MainForm.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$MainForm.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $MainForm.ShowDialog()
}
#endregion Source: MainForm.psf

#region Source: Globals.ps1
	function Fix-XML
	{
		param ([String]$Text)
		
		$Mapping = @{
			'&lt;' = [System.Char]60;
			'&gt;' = [System.Char]62;
			'&quot;' = [System.Char]34;
			'&apos;' = [System.Char]39;
			'&amp;' = [System.Char]38;
		}
		
		$Text = [Regex]::Replace($Text, [System.Environment]::NewLine, [String]::Empty)
		
		foreach ($k in $Mapping.Keys)
		{
			$Text = [Regex]::Replace($Text, $k, [String]$Mapping[$k])
		}
	
		Write-Output $Text.ToString()
	}
	
	function Get-XMLData
	{
		param (
			[String]$Text,
			[String]$FilterTag
		)
		$Lookup = [System.String]::Format("(?<=<.*{0}.*>)(.*)(?=</.*{0}>)", $FilterTag)
		$Text = [regex]::match([regex]::Replace($Text, '(?:\r|\n)', ''), $Lookup).Groups[1].Value
		Write-Output $Text.ToString()
	}
	
	function Format-XML
	{
		Param ([String]$XML)
		
		$Out = New-Object System.IO.StringWriter
		$Doc = New-Object system.xml.xmlDataDocument
		$Doc.LoadXml($XML)
		$Writer = New-Object System.XMl.XmlTextWriter($Out)
		$Writer.Formatting = [System.Xml.Formatting]::Indented
		$Writer.Indentation = 4
		$Doc.WriteContentTo($Writer)
		$Writer.Flush()
		$Out.Flush()
		
		Write-Output $Out.ToString()
	}
	
	function ConvertXmlNodeTo-TreeNode
	{
		param (
			[System.Xml.XmlNode]$xmlNode,
			[System.Windows.Forms.TreeNodeCollection]$treeNodes
		)
		
		$xmlNodeName = if ($xmlNode.LocalName -eq 'Name')	{
							$xmlNode.Name
						}
						else
						{
							$xmlNode.LocalName
						}
		
		[System.Windows.Forms.TreeNode]$newTreeNode = $treeNodes.Add($xmlNodeName);
		
		switch ($xmlNode.NodeType)
		{
			'ProcessingInstruction' {
				$newTreeNode.Text = '<?' + $xmlNodeName + ' ' + $xmlNode.Value + '?>';
				break;
			}
			'XmlDeclaration' {
				$newTreeNode.Text = '<?' + $xmlNodeName + ' ' + $xmlNode.Value + '?>';
				break;
			}
			'Element' {
				$newTreeNode.Text = '<' + $xmlNodeName + '>';
				break;
			}
			'Attribute' {
				$newTreeNode.Text = 'ATTRIBUTE: ' + $xmlNodeName;
				break;
			}
			'Text' {
				$newTreeNode.Text = $xmlNode.Value;
				break;
			}
			'CDATA' {
				$newTreeNode.Text = $xmlNode.Value;
				break;
			}
			'Comment'{
				$newTreeNode.Text = "<!--" + $xmlNode.Value + "-->";
				break;
			}
		}
		
		if ($xmlNode.Attributes -ne $null)
		{
			foreach ($attribute in $xmlNode.Attributes)
			{
				ConvertXmlNodeTo-TreeNode -xmlNode $attribute -treeNodes $newTreeNode.Nodes;
			}
		}
		foreach ($childNode in $xmlNode.ChildNodes)
		{
			ConvertXmlNodeTo-TreeNode -xmlNode $childNode -treeNodes $newTreeNode.Nodes;
		}
	}#endregion Source: Globals.ps1

#Start the application
Main ($CommandLine)
